server:
  port: 1992

spring:
  application:
    name: cargo-process-tracking
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  messages:
    basename: messages
  security:
    user:
      name: admin
      password: password
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    protocol: smtp
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: Admin
      last-name: User
      email: admin@example.com
    database:
      schema-update: true
      type: postgres
    job-execution:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 5
      max-jobs-per-acquisition: 5
      lock-time-in-millis: 300000
      wait-time-in-millis: 5000
      deployment-aware: true
    generic-properties:
      properties:
        historyTimeToLive: P30D